name: 'GriefPreventionFlags'
main: me.ryanhamshire.GPFlags.GPFlags
depend: [GriefPrevention]
softdepend: [mcMMO]
version: 4.5.2
commands:
   setclaimflag:
      description: Sets a flag on a GriefPrevention land claim.
      usage: /SetClaimFlag <flag> <optional parameters>
      aliases: [setflag, placeflag, putflag, claimflag, placeclaimflag, putclaimflag]
      permission: gpflags.setflag
   unsetclaimflag:
      description: Un-sets (removes) a flag on a GriefPrevention land claim.
      usage: /UnSetClaimFlag <flag>
      aliases: [unsetflag, removeflag, unclaimflag, removeclaimflag]
      permission: gpflags.unsetflag
   setdefaultclaimflag:
      description: Sets a flag on all GriefPrevention land claims.
      usage: /SetDefaultClaimFlag <flag> <optional parameters>
      aliases: [setdefaultflag, placedefaultflag, putdefaultflag, defaultclaimflag, placedefaultclaimflag, putdefaultclaimflag]
      permission: gpflags.defaultflags
   unsetdefaultclaimflag:
      description: Un-sets (removes) a default flag from all GriefPrevention land claims.
      usage: /UnSetClaimFlag <flag>
      aliases: [unsetdefaultflag, removedefaultflag, removedefaultclaimflag]
      permission: gpflags.defaultflags
   listclaimflags:
      description: Lists all the flags currently set on a GriefPrevention land claim.
      usage: /ListClaimFlags
      aliases: [listclaimflags, claimflags, listflags]
      permission: gpflags.listflags
   setworldflag:
      description: Sets a flag on an entire world.
      usage: /SetWorldFlag <flag> <optional parameters>
      aliases: [placeworldflag, putworldflag, worldflag]
      permission: gpflags.setworldflag
   unsetworldflag:
      description: Un-sets (removes) a world-level flag.
      usage: /UnSetWorldFlag <flag>
      aliases: [unsetworldflag, removeworldflag, unworldflag]
      permission: gpflags.unsetworldflag
   setserverflag:
      description: Sets a flag everywhere.
      usage: /SetServerFlag <flag> <optional parameters>
      aliases: [placeserverflag, putserverflag, serverflag]
      permission: gpflags.setserverflag
   unsetserverflag:
      description: Un-sets (removes) a server-level flag.
      usage: /UnSetServerFlag <flag>
      aliases: [unsetserverflag, removeserverflag, unserverflag]
      permission: gpflags.unsetservrflag
   gpfreload:
      description: Reloads GriefPrevention Flags configuration settings from its config file.
      usage: /GPFReload
      permission: gpflags.reload
permissions:
    gpflags.admin.*:
        description: Grants all administrative functionality.
        children:
            gpflags.setflag: true
            gpflags.defaultflags: true
            gpflags.unsetflag: true
            gpflags.setworldflag: true
            gpflags.unsetworldflag: true
            gpflags.setserverflag: true
            gpflags.unsetserverflag: true
            gpflags.listflags: true
            gpflags.reload: true
            gpflags.allflags: true
            gpflags.bypass: true
    gpflags.setflag:
        description: Grants permission to use /SetClaimFlag.
        default: op
    gpflags.unsetflag:
        description: Grants permission to use /UnSetClaimFlag.
        default: op
    gpflags.setworldflag:
        description: Grants permission to use /SetWorldFlag.
        default: op
    gpflags.unsetworldflag:
        description: Grants permission to use /UnSetWorldFlag.
        default: op
    gpflags.setserverflag:
        description: Grants permission to use /SetServerFlag.
        default: op
    gpflags.unsetserverflag:
        description: Grants permission to use /UnSetServerFlag.
        default: op
    gpflags.defaultflags:
        description: Grants permission to use /SetDefaultClaimFlag and /UnSetDefaultClaimFlag.
        default: op
    gpflags.listflags:
        description: Grants permission to use /ListClaimFlags.
        default: op
    gpflags.reload:
        description: Grants permission to use /GPFReload.
        default: op
    gpflags.allflags:
        description: Grants permission to apply/remove all flags.
        default: op
    gpflags.bypass:
        description: Makes a player immune to the limitations of flags like CommandBlackList, NoEnter, and NoFlight.
        default: op